spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fincore
    username: postgres
    password: postgres

  flyway:
    schemas: user
    default-schema: user
    table: flyway_schema_history

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "health,info"